Dserver/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),

    path('api/', include('Main.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

Main/api/urls.py
# for APIs only
from django.urls import path
from .import views

app_name = 'Main'
urlpatterns = [
    path('ar', views.ar_view, name="ar_details"),
    path('purchase', views.purchase_view, name="purchase_details"),
    path('sales', views.sales_view, name="sale_details"),
    path('parties', views.sales_view, name="party_details"),
    
]

Main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    #routes
     path('', views.login_view, name="login"),
     path('logout', views.logout_user, name="logout"),
     path('dashboard', views.dashboard_view, name="dashboard"),
     path('register', views.register_view, name="register"),

     #tables
     path('artable', views.ar_table_view, name="artable"),
     path('sale', views.sale_table_view, name="sale"),
     path('purchase', views.purchase_table_view, name="purchase"),
     path('parties', views.parties_table_view, name="parties"),

     #password reset
     path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
          name='password_change_done'),
     path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
          name='password_change'),
     path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
          name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm_form.html'), 
               name='password_reset_confirm'),
     path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), 
               name='password_reset'),
     path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
          name='password_reset_complete'),


]

Main/models.py
from django.db import models

class AR(models.Model):
    db = models.CharField(max_length=50, default="none")
    customer = models.CharField(max_length=100, default="none")
    invoice_amt = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    receipt_amt = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    balance = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    address = models.CharField(max_length=150, default="none")
    city = models.CharField(max_length=50, default="none")
    state = models.CharField(max_length=50, default="none")
    phone = models.CharField(max_length=150, default="none")
    email = models.CharField(max_length=250, default="none")

    def __str__(self):
        return self.db

    class Meta:
        verbose_name = 'AR List'


class Parties(models.Model):

    # specifying choices for parties table (type)
    TYPE_CHOICES = (
        ("supplier", "Supplier"),  # "actual value", "human read name"
        ("customer", "Customer"),
        ("location", "Location"),
    )

    db = models.CharField(max_length=50, default="none")
    name = models.CharField(max_length=50, default="none")
    type = models. CharField(max_length=20, choices=TYPE_CHOICES, default="none")
    address = models.CharField(max_length=150, default="none")
    address_2 = models.CharField(max_length=150, default="none")
    city = models.CharField(max_length=20, default="none")
    state = models.CharField(max_length=20, default="none")
    zip = models.IntegerField(null=True)
    country = models.CharField(max_length=20, default="none")
    phone = models.CharField(max_length=15, default="none")
    phone2 = models.CharField(max_length=15, default="none")
    email = models.CharField(max_length=50, default="none")

    def __str__(self):
        return self.db

    class Meta:
        verbose_name = 'Parties List'

class Purchases(models.Model):
    db = models.CharField(max_length=50, default="none")
    tdate = models.CharField(max_length=50, default="none")
    supplier = models.CharField(max_length=50, default="none")
    supplier_print_name = models.CharField(max_length=50, default="none")
    item = models.CharField(max_length=250, default="none")
    quantity = models.DecimalField(decimal_places=4, max_digits=10, null=True, default="0.00")
    unit_price = models.DecimalField(decimal_places=4, max_digits=10, null=True, default="0.00")
    extended = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    fob_unit_price = models.DecimalField(decimal_places=4, max_digits=10, null=True, default="0.00")
    cogs_unit_price = models.DecimalField(decimal_places=4, max_digits=10, null=True, default="0.00")
    cogs_extended = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    debit = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    credit = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")

    def __str__(self):
        return self.db

class Sales(models.Model):
    db = models.CharField(max_length=50, default="none")
    location_id = models.IntegerField(null=True)
    tdate = models.CharField(max_length=50, default="none")
    customer = models.CharField(max_length=150, default="none")
    item = models.CharField(max_length=150, default="none")
    quantity = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    unit_price = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    extended = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    foreign_extended = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    tax = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    cogs_extended = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    debit = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")
    credit = models.DecimalField(decimal_places=2, max_digits=10, null=True, default="0.00")

    def __str__(self):
        return self.db

    class Meta:
        verbose_name = 'Sales List'

Main/api/views.py
from rest_framework import status
from rest_framework.response import Response 
from rest_framework.decorators import api_view

from Main.models import *
from .serializers import *

api_view(['GET', 'POST'])
def ar_view(request):
    try:
        if request.method == 'GET':
            ar_data = AR.objects.all()
            serializer = AR_Serializer(ar_data, many=True)
            return Response(serializer.data)
        elif request.method == 'POST':
            serializer = AR_Serializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    except AR.DoesNotExist:
        return Response({'message': 'Data does not exist'}, status=status.HTTP_404_NOT_FOUND)


@api_view(['GET', 'POST'])
def purchase_view(request):
    try:
        if request.method == 'GET':
            purchase_data = Purchases.objects.all()
            serializer = Purchases_Serializer(purchase_data, many=True)
            return Response(serializer.data)
        elif request.method == 'POST':
            serializer = Purchases_Serializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    except Purchases.DoesNotExist:
        return Response({'message': 'Data does not exist'}, status=status.HTTP_404_NOT_FOUND)


@api_view(['GET', 'POST'])
def sales_view(request):
    try:
        if request.method == 'GET':
            sales_data = Sales.objects.all()
            serializer = Sales_Serializer(sales_data, many=True)
            return Response(serializer.data)
        elif request.method == 'POST':
            serializer = Sales_Serializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    except Sales.DoesNotExist:
        return Response({'message': 'Data does not exist'}, status=status.HTTP_404_NOT_FOUND)


@api_view(['GET', 'POST'])
def parties_view(request):
    try:
        if request.method == 'GET':
            parties_data = Parties.objects.all()
            serializer = Parties_Serializer(parties_data, many=True)
            return Response(serializer.data)
        elif request.method == 'POST':
            serializer = Parties_Serializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_201_CREATED)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    except Parties.DoesNotExist:
        return Response({'message': 'Data does not exist'}, status=status.HTTP_404_NOT_FOUND)

Main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect

from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
from tablib import Dataset

from django.contrib.auth.forms import UserCreationForm
from Account.forms import RegistrationForm
from Account.models import Users
from .resources import *
from .models import *
from .filters import *

# ------------------ routes --------------- #

def register_view(request):
    logout_user(request)
    context={}
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            #user = authenticate(email=email, password=raw_password)
            #messages.info(request, 'User account is created')
            return redirect('login')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'register.html', context)

def login_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.info(request, 'Email or Password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect("login")


@login_required(login_url='login')
def dashboard_view(request):
    context = {}
    return render(request, "Main/dashboard.html", context)


# ----------------- tables ---------------- #

@login_required(login_url='login')
def ar_table_view(request):
    artable_list = AR.objects.all()
    myfilter = arFilter(request.GET, queryset=artable_list)
    artable_list = myfilter.qs
    context = {'artable': artable_list, 'myfilter':myfilter}

    if request.method == 'POST':
        ar_resource = AR_resource()
        dataset = Dataset()
        new_ar = request.FILES['input_data']
        imported_data = dataset.load(
            new_ar.read().decode('utf-8'), format='csv')
        result = ar_resource.import_data(dataset, dry_run=True)

        if result.has_validation_errors() or result.has_errors():
            return JsonResponse({'message': 'validation error'}, status=500)
        else:
            ar_resource.import_data(dataset, dry_run=False)
            return JsonResponse({'message': 'File uploaded successfully'}, status=200)
    return render(request, "Main/artable.html", context)


@login_required(login_url='login')
def parties_table_view(request):
    partie_list = Parties.objects.all()
    myfilter = partieFilter(request.GET, queryset=partie_list)
    partie_list = myfilter.qs
    context = {'partiestable': partie_list, 'myFilter':myfilter}

    if request.method == 'POST':
        partie_resource = Parties_resource()
        dataset = Dataset()
        new_partie = request.FILES['input_data']
        imported_data = dataset.load(
            new_partie.read().decode('utf-8'), format='csv')
        result = partie_resource.import_data(dataset, dry_run=True)

        if result.has_validation_errors() or result.has_errors():
            return JsonResponse({'message': 'validation error'}, status=500)
        else:
            partie_resource.import_data(dataset, dry_run=False)
            return JsonResponse({'message': 'File uploaded successfully'}, status=200)
    return render(request, "Main/partiestable.html", context)


@login_required(login_url='login')
def purchase_table_view(request):
    purchase_list = Purchases.objects.all()
    myfilter = purchaseFilter(request.GET, queryset=purchase_list)
    purchase_list = myfilter.qs
    context = {'purchasetable': purchase_list, 'myFilter':myfilter}

    if request.method == 'POST':
        purchase_resource = Purchase_resource()
        dataset = Dataset()
        new_purchase = request.FILES['input_data']
        imported_data = dataset.load(
            new_purchase.read().decode('utf-8'), format='csv')
        result = purchase_resource.import_data(dataset, dry_run=True)

        if result.has_validation_errors() or result.has_errors():
            return JsonResponse({'message': 'validatiion error'}, status=500)
        else:
            purchase_resource.import_data(dataset, dry_run=False)
            return JsonResponse({'message': 'File uploaded successfully'}, status=200)
    return render(request, "Main/purchasetable.html", context)


@login_required(login_url='login')
def sale_table_view(request):
    sales_list = Sales.objects.all()
    myfilter = saleFilter(request.GET, queryset=sales_list)
    sales_list = myfilter.qs
    context = {'saletable': sales_list, 'myfilter':myfilter}

    if request.method == 'POST':
        sale_resource = Sale_resource()
        dataset = Dataset()
        new_sale = request.FILES['input_data']
        imported_data = dataset.load(
            new_sale.read().decode('utf-8'), format='csv')
        result = sale_resource.import_data(dataset, dry_run=True)

        if result.has_validation_errors() or result.has_errors():
            return JsonResponse({'message': 'validation error'}, status=500)
        else:
            sale_resource.import_data(dataset, dry_run=False)
            return JsonResponse({'message': 'File uploaded successfully'}, status=200)
    return render(request, "Main/saletable.html", context)

Main/templates/Main/artable.html
{% extends 'base.html' %} {% block content %}

<!-- main content -->
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-sm-4 px-2">
            <h1 class="mt-4">Addons</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li class="breadcrumb-item active">AR</li>
            </ol>
            <!--table model filter-->
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between flex-wrap">
                    <div><i class="fas fa-table mr-1"></i> AR Data</div>
                    <div>
                        <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#uploadModal">
                            <i class="fas fa-upload"></i> Upload File
                        </button>
                        <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#filterModal">
                            <i class="fas fa-filter mr-1"></i> Advance Filter
                        </button>
                    </div>
                </div>
                <!--import modal -->
                <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="uploadModalCenterTitle">Upload Files</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3 mt-3">
                                            <form action="" id="upload-form">{% csrf_token %}
                                                <div class="form-group mb-3">
                                                    <div class="custom-file">
                                                        <input type="file" class="custom-file-input" name="input_data"
                                                            accept=".csv, text/csv" id="file_input"
                                                            oninput="input_filename();" />
                                                        <label id="file_input_label" class="custom-file-label"
                                                            for="image">Select file - (csv only)</label>
                                                    </div>
                                                </div>
                                            </form>
                                            <button onclick="upload();" id="upload_btn"
                                                class="btn btn-primary">Upload</button>

                                            <button class="btn btn-primary d-none" id="loading_btn" type="button"
                                                disabled>
                                                <span class="spinner-border spinner-border-sm" role="status"
                                                    aria-hidden="true"></span>
                                                Uploading...
                                            </button>
                                            <button type="button" id="cancel_btn" class="btn btn-dark d-none">Cancel
                                                upload</button>
                                        </div>
                                        <div id="progress_wrapper" class="d-none">
                                            <label id="progress_status"></label>
                                            <div class="progress mb-3">
                                                <div id="progress"
                                                    class="progress-bar progress-bar-striped progress-bar-animated bg-success"
                                                    role="progressbar" aria-valuenow="25" aria-valuemin="0"
                                                    aria-valuemax="100"></div>
                                            </div>
                                        </div>

                                        <div id="alert_wrapper"></div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <!--filter modal-->
                <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="filterModalCenterTitle">Advance Filter</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="GET">
                                    <div class="form-group">
                                        <input type="text" name="db" value="" class="form-control" id="id_db"
                                            placeholder="Enter Database">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="customer" value="" class="form-control"
                                            id="id_customer" placeholder="Enter Customer">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="city" class="form-control" id="id_city"
                                            placeholder="Enter City">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="phone" class="form-control" id="id_phone"
                                            placeholder="Enter Phone">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- tables setting -->
                <div class="card-body p-sm-4 p-2">
                    <div class="table-responsive">
                        <table class="table table-bordered table-sm" id="datatable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>DB</th>
                                    <th>Customer</th>
                                    <th>Invoice</th>
                                    <th>Receipt</th>
                                    <th>Balance</th>
                                    <th>Address</th>
                                    <th>City</th>
                                    <th>State</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>DB</th>
                                    <th>Customer</th>
                                    <th>Invoice</th>
                                    <th>Receipt</th>
                                    <th>Balance</th>
                                    <th>Address</th>
                                    <th>City</th>
                                    <th>State</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                {% for i in artable %}
                                <tr>
                                    <td>{{i.db}}</td>
                                    <td>{{i.customer}}</td>
                                    <td>{{i.invoice_amt}}</td>
                                    <td>{{i.receipt_amt}}</td>
                                    <td>{{i.balance}}</td>
                                    <td>{{i.address}}</td>
                                    <td>{{i.city}}</td>
                                    <td>{{i.state}}</td>
                                    <td>{{i.phone}}</td>
                                    <td>{{i.email}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!--footerstart-->
    <!--footerend-->

    {% endblock %}

Main/templates/Main/dashboard.html
<!-- After rest actual path-->

{% extends 'base.html' %}

{% block content %}
<!-- main content -->
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-sm-4 px-2">
          <h1 class="mt-4">Core</h1>
          <ol class="breadcrumb mb-4">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
          </ol>
      <!-- if content put here-->

      <!--contentend-->
          </div>
      </main>
<!--footerstart-->
<!--footerend-->


{% endblock %}